DROP TABLE PARTICIPATOR CASCADE CONSTRAINTS;
DROP TABLE REVIEWER CASCADE CONSTRAINTS;
DROP TABLE AUTHOR CASCADE CONSTRAINTS;
DROP TABLE TOPICS_OF_INTERESTS CASCADE CONSTRAINTS;
DROP TABLE WRITES CASCADE CONSTRAINTS;
DROP TABLE PAPER CASCADE CONSTRAINTS;
DROP TABLE REVIEWS CASCADE CONSTRAINTS;

CREATE TABLE PARTICIPATOR(
    Email VARCHAR2(250) NOT NULL PRIMARY KEY,
    FirstName VARCHAR2(25) NOT NULL,
    LastName VARCHAR2(25) NOT NULL,
    Minit VARCHAR2(10),
    Phone VARCHAR2(15),
    Affiliation VARCHAR2(250)
);
    
CREATE TABLE REVIEWER(
    RevEmail VARCHAR2(250),
    CONSTRAINT FK_RevEmail FOREIGN KEY (RevEmail) REFERENCES PARTICIPATOR (Email) ON DELETE CASCADE
);
    
CREATE TABLE AUTHOR(
    AuthorEmail VARCHAR2(250),
    CONSTRAINT FK_AuthorEmail FOREIGN KEY (AuthorEmail) REFERENCES PARTICIPATOR (Email) ON DELETE CASCADE
);

CREATE TABLE TOPICS_OF_INTERESTS(
    ReviewEmail VARCHAR2(250),
    Topic VARCHAR2(500) NOT NULL,
    CONSTRAINT FK_ReviewEmail FOREIGN KEY (ReviewEmail) REFERENCES PARTICIPATOR (Email) ON DELETE CASCADE,
    CONSTRAINT PK_TOPICS_OF_INTERESTS_TABLE PRIMARY KEY (ReviewEmail, Topic)
);
    
CREATE TABLE PAPER(
    PaperID INT PRIMARY KEY,
    Title VARCHAR2(250),
    Abstract VARCHAR2 (1000),
    File_Name VARCHAR2(100),
    ContactAuthorEmail VARCHAR2(250) NOT NULL,
    CONSTRAINT FK_ContactAuthorEmail FOREIGN KEY (ContactAuthorEmail) REFERENCES PARTICIPATOR (Email) ON DELETE CASCADE
);

CREATE TABLE WRITES(
    PaperID INT,
    AuthorEmail VARCHAR2(2000),
    CONSTRAINT FK_PaperID FOREIGN KEY (PaperID) REFERENCES PAPER(PaperID) ON DELETE CASCADE,
    CONSTRAINT PK_WRITES PRIMARY KEY (PaperID, AuthorEmail)
);

CREATE TABLE REVIEWS(
    ReviewerEmail VARCHAR2(250),
    ReviewPaperID INT,
    ReviewDate DATE,
    TechMerit INT CHECK (TechMerit>=1 AND TechMerit<=10),
    Readability INT CHECK (Readability>=1 AND Readability<=10),
    Originality INT CHECK (Originality>=1 AND Originality<=10),
    Relevance INT CHECK (Relevance>=1 AND Relevance<=10),
    OverallRecomm INT CHECK (OverallRecomm>=1 AND OverallRecomm<=10),
    CommentForCommittee VARCHAR2(1000),
    CommentForAuthor VARCHAR2(1000),
    CONSTRAINT FK_ReviewPaperID FOREIGN KEY (ReviewPaperID) REFERENCES PAPER(PaperID) ON DELETE CASCADE,
    CONSTRAINT FK_ReviewerEmail FOREIGN KEY (ReviewerEmail) REFERENCES PARTICIPATOR (Email) ON DELETE CASCADE,
    CONSTRAINT PK_REVIEWS PRIMARY KEY (ReviewerEmail, ReviewPaperID)
);
